name: my-main-workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/7 * * * *'
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use My Workflow
        uses: RachitGupta008/github-actions/blob/master/.github/workflows/schedule.yaml@main
